Algoritmo "problema retangulo"
Var

altura, base, area, perimetro, diagonal: real

Inicio

  escreva("Digite a base: ")
  leia (base)
  escreval

  escreva("Digite a altura: ")
  leia (altura)
  escreval


  area <- base * altura
  perimetro <- 2 * (base + altura)
  diagonal <-  RaizQ(Exp (base,2) + Exp (altura,2))

  escreval()
  escreval ("Área: ", area:8:4)
  escreval ("Perimetro: ", perimetro:8:4)
  escreval ("Diagonal: ", diagonal:8:4)

Fimalgoritmo